# Generated by Django 3.0.8 on 2020-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0013_auto_20200906_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='range',
            field=models.PositiveIntegerField(default=10, verbose_name='range'),
        ),
    ]
